public class CafeteraDriver {
    public static void main(String[] args) {
        Cafetera caf = new Cafetera(5001,1000,1500,50);
        caf.americano();
        caf.expreso();
        caf.capuchino();
        caf.check();
        caf.americano();
        caf.americano();
        caf.americano();
        caf.check();
        caf.expreso();
        caf.expreso();
        caf.expreso();
        caf.check();
        caf.capuchino();
        caf.capuchino();
        caf.capuchino();
        caf.check();
        caf.americano();
        caf.americano();
        caf.americano();
        caf.expreso();
        caf.expreso();
        caf.expreso();
        caf.capuchino();
        caf.capuchino();
        caf.capuchino();
        caf.americano();
        caf.americano();
        caf.americano();
        caf.expreso();
        caf.expreso();
        caf.expreso();
        caf.capuchino();
        caf.capuchino();
        caf.capuchino();
        caf.check();
        caf.expreso();
        caf.expreso();
        caf.capuchino();
        caf.capuchino();
        caf.capuchino();
        caf.americano();
        caf.capuchino();
        caf.expreso();
        caf.check();
        caf.americano();

    }
}
